### ISSUE TITLE
Cannot be compiled with Java 8 anymore

### ISSUE THREAD

**Issue by udemaddalena** [rfoltyns/log4j2-elasticsearch-examples#3]
I cloned the project and then ran 'mvn clean install' with java 8 on Windows and Linux, after which I received the following error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for log4j2-elasticsearch examples 0.0.1-SNAPSHOT:
[INFO]
[INFO] log4j2-elasticsearch examples ...................... SUCCESS [  0.316 s]
[INFO] log4j2-elasticsearch-jest-springboot ............... FAILURE [  2.625 s]
[INFO] log4j2-elasticsearch-hc-springboot ................. SKIPPED
[INFO] log4j2-elasticsearch-hc-one-jar .................... SKIPPED
[INFO] log4j2-elasticsearch-ahc-one-jar ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.101 s
[INFO] Finished at: 2023-02-25T21:00:12+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:3.0.3:repackage (default) on project log4j2-elasticsearch-jest-springboot: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:3.0.3:repackage failed: Unable to load the mojo 'repackage' in the plugin 'org.springframework.boot:spring-boot-maven-plugin:3.0.3' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/springframework/boot/maven/RepackageMojo has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0

java Version: 1.8.0_352
maven Version: 3.9.0

The code compiles with Java 17, but the examples do not run.

**Comment by udemaddalena** [comment]
After i added <version>${spring-boot.version}</version> in the Plugin section, it works with java 8.

**Comment by rfoltyns** [comment]
I'm glad you got it working :clap: 

Java 8 is slowly getting deprecated here and there, so errors like these might not be uncommon.

Would you be interested in creating a PR for this?

**Comment by rfoltyns** [comment]
[PR](https://github.com/rfoltyns/log4j2-elasticsearch-examples/pull/4) merged. Thank you! :+1:
