### ISSUE TITLE
log4j2.yml not working

### ISSUE THREAD

**Issue by viratbiz** [rfoltyns/log4j2-elasticsearch-examples#5]
When I am using NonEmpty Filter in log4j2.yml, there is error saying `2023-04-07 12:43:41,063 main ERROR JacksonJsonLayout contains an invalid element or attribute "NonEmptyFilter"
2023-04-07 12:43:41,357 restartedMain ERROR JacksonJsonLayout contains an invalid element or attribute "NonEmptyFilter"`

But its working fine in log4j2.xml

Log4j2.yml:
`Configuration:
  Appenders:
    Console:
      name: ConsoleAppender
      target: SYSTEM_OUT
      PatternLayout:
        pattern: "%d %highlight{%-5level}{FATAL=bg_red, ERROR=red, WARN=yellow, INFO=green} [%t] %-c{1.} - %C{1.} - %M - %msg %n"
    Elasticsearch:
      name: elasticsearch
      IndexName:
        indexName: log4j2
      JacksonJsonLayout:
        NonEmptyFilter:
        VirtualProperty:
          -
            name: log
            value: $${ctx:log:-}
            dynamic: true
            writeRaw: true
          -
            name: context
            value: $${ctx:context:-}
            dynamic: true
            writeRaw: true
      AsyncBatchDelivery:
        batchSize: 2000
        deliveryInterval: 1000
        JestHttp:
          serverUris: http://localhost:9200
          XPackAuth:
            BasicCredentials:
              username: elastic
              password: elastic
  Loggers:
    Root:
      level: info
      AppenderRef:
        -
          ref: ConsoleAppender
        -
          ref: elasticsearch
`

Log4j2.xml:
`<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <Appenders>
        <Console name="ConsoleAppender" target="SYSTEM_OUT">
            <PatternLayout pattern="%d %highlight{%-5level}{FATAL=bg_red, ERROR=red, WARN=yellow, INFO=green} [%t] %-c{1.} - %C{1.} - %M - %msg %n"/>
        </Console>
        <Elasticsearch name="elasticsearch">
            <IndexName indexName="log4j2"/>
            <JacksonJsonLayout>
                <NonEmptyFilter/>
                <VirtualProperty name="log" value="$${ctx:log:-}" dynamic="true" writeRaw="true"/>
                <VirtualProperty name="context" value="$${ctx:context:-}" dynamic="true" writeRaw="true"/>
            </JacksonJsonLayout>
            <AsyncBatchDelivery batchSize="2000" deliveryInterval="1000">
                <JestHttp serverUris="http://localhost:9200/">
                    <XPackAuth>
                        <BasicCredentials username="elastic" password="elastic" />
                    </XPackAuth>
                </JestHttp>
            </AsyncBatchDelivery>
        </Elasticsearch>
    </Appenders>
    <Loggers>
        <Root level="info">
            <AppenderRef ref="ConsoleAppender"/>
            <AppenderRef ref="elasticsearch"/>
        </Root>
    </Loggers>
</Configuration>`

**Comment by rfoltyns** [comment]
I can't figure what's broken unfortunately. Could you reformat your yaml snippet, please? "```yaml" might help.

I never tried modelling anything complicated with yaml tbh, but correct indentations are very important with that beast.

**Comment by viratbiz** [comment]
I dont think its an indentation problem. The error it is showing is: 
![Image 07-04-23 at 3 18 PM](https://user-images.githubusercontent.com/122271047/230587702-29fa3df0-793c-45a8-9825-5753483ac855.jpeg)

I am also attaching the snippet of yml file
![Image 07-04-23 at 3 22 PM](https://user-images.githubusercontent.com/122271047/230588118-22fb9319-c725-44a4-b90f-739a5044adc7.jpeg)

**Comment by rfoltyns** [comment]
Thank you for the snippet. But I still can't copy/paste it.

How do you expect me to reproduce it if all I have is:
1.  A generic ERROR log produced by Log4j2 library on literally any config mishap
2.  Config that "looks like this" - might be enough, but could you make it a bit easier for me, please?

Could you provide a full, formatted config file that you use to get this error, please?

**Comment by viratbiz** [comment]
Please find the yml file here: [https://codeshare.io/BAe6Ry](url) and xml file here: [https://codeshare.io/QnNQRR](url)

**Comment by viratsharma56** [comment]
Hi,
I hope you have gone through the files. Can you let me know if there are any suggestions?

**Comment by rfoltyns** [comment]
Unfortunately, yml link is not working anymore.

Could you create the fork of this repo and put the files there, please? I believe that's the most robust way to handle it (and a fairly decent practice while working with Github repos)

**Comment by rfoltyns** [comment]
YAML examples added.

I believe you were missing `{}` after object with no attributes.

```yaml
NonEmptyFilter: {}
```

Feel free to re-open if you have more issues with YAML config.
